### ISSUE TITLE
Showing Delorean stable/* links on the landing page.

### ISSUE THREAD

**Issue by chkumar246** [redhat-openstack/trunk.rdoproject.org#2]
It would be good to show RDO liberty snapshots link  http://rdoproject.org/repos/openstack-trunk/ on the landing page of trunk.rdoproject.org.

**Comment by apevec** [comment]
Actually, we want links to Delorean Kilo/Liberty instances on trunk.rdo homepage:

http://trunk.rdoproject.org/centos7-kilo/report.html
http://trunk.rdoproject.org/centos7-liberty/report.html
